config/routes.rb
Rails.application.routes.draw do
  root 'ruche#index'
  get 'form' => 'ruche#form'
  get 'info' => 'ruche#info'
  post 'form' => 'ruche#create'
  get 'donnees' => 'ruche#donnees'

end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/ruche_controller.rb
class RucheController < ApplicationController

	def index
	end

	def info
	end

	def form
	end
	
	def create
		@contact = Contact.new(params_contact)
		if @contact.save
			UserMailer.envoi_form_email.deliver
			redirect_to root_path, notice: "Merci de votre participation !"
		else
			render 'form'
		end
	end

	def donnees
		@contact = Contact.all
	end

	private

	def params_contact
		params.require(:contact).permit(:nom, :prenom, :mail, :avis)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ruche_helper.rb
module RucheHelper
end

app/views/layouts/_footer.html.erb
<div class="footer">
	<div class="adresse">
	 
	 <p>Simplon.ve</br>
	  	Pôleyrieux</br>
	  	Aric industries</br>
	  	07 160 Le Cheylard
	 </p>
	</div>
	<div class="createurs">
	site réalisé par la promotion Simplon ve - 2015
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  		<title>TERRA RUCHES</title>
  		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  		<%= csrf_meta_tags %>
  </head>
   	
  <header>TERRA RUCHES</header>

  <body>
		
     <div class="photo1">
      <%= image_tag("apiculture2.jpg")%>
     </div>
		 <div class="container">
			<%= yield %>
		 </div>
		<%= render "layouts/footer" %>
  </body>
</html>

app/views/ruche/donnees.erb
<% @contact.each do |contact| %>
	<div class="donnees">Nom : <%= contact.nom %></div>
	<div class="donnees">Prénom : <%= contact.prenom %></div>
	<div class="donnees">Mail : <%= contact.mail %></div>
	<div class="donnees">Avis : <%= contact.avis %></div>
<% end %>

app/views/ruche/form.html.erb
<div class="formulaire"> 
<%= form_for :contact do |f| %>

   	<div class="contact-champ">
		<%= f.label :nom %>
		<%= f.text_field :nom %>
	</div>

	<div class="contact-champ">
		<%= f.label :prenom %>
		<%= f.text_field :prenom %>
	</div>

	<div class="contact-champ">
		<%= f.label :mail %>
		<%= f.text_field :mail %>
	</div>	

	<div class="contact-champ">
		<%= f.text_area :avis, placeholder: "Votre avis nous intéresse..." %>
	</div>	

    <div class="envoyer">
		<%= link_to (image_tag('home.png', title:"page d'accueil")), root_path, { :class=>"retour" } %>
		<%= f.submit "Submit", :type => :image, :src => image_path("envoyer1.png"), :class => "envoyer_img" %>
    </div>
<% end %>
</div>

app/views/ruche/index.html.erb
<div class="container1">

    <h3 class="action">Apiculteurs et propriétaires de terrain, nous avons besoin de vos propositions pour developper cette action écologique, durable et citoyenne.</h3>
    <div class="contact"> 
      <p>contactez-nous</p>
      <%= link_to (image_tag('enveloppe1.svg', width: 150, title:"contactez-nous")), form_path, { :class=>"contactez_nous" } %> 
    </div> 

    <h2 class="text-center">L' abeille </h2> 

    <div class="texte1">
    
    	 <p class="colonne1">Les abeilles sont indispensables  à la pollinisation de plus de 70% des plantes et au maintien de la biodiversité.
       </p>

    	 <p class="colonne1">Les abeilles disparaissent en masse ces dernières années. Les facteurs se combinent d’après les scientifiques.
    
        <%= link_to (image_tag('plus1.svg', width: 70, title:"plus d'infos")), info_path, { :class=>"croix" } %>
      </p>

    </div>
  </div>

<div class="container2">
    
      <h2 class="text-center">Le projet</h2>

      <div class="texte2">
        <p>Les apiculteurs recherchent des terrains pour accueillir leurs ruches et améliorer la diversité et la qualité du miel produit.</p>

        <p id="bloc_couleur2">Vous êtes, un particulier, une entreprise, une collectivité, vous êtes propriètaires de terrains inexploités, vous êtes un ardent défenseur de la qualité de vie, soutenez les apiculteurs et leurs abeilles, proposez un terrain pour accueillir des ruches.

        <p>Ce projet a pour but de mettre en relation les apiculteurs avec les propriétaires de terrain.</p>

        <p></p>
    </div> 
    
</div>

app/views/ruche/info.html.erb
<div class="container3">

    <h2 class="text-center">Les abeilles, indispensables pollinisateurs des plantes</h2>

    <div class="texte3">

     	<p class="colonne">La plus part des plantes que nous connaissons ont besoin des abeilles, et plus largement des insectes pollinisateurs, pour assurer leur reproduction.<br>
        Alors que l’abeille buttine les fleurs d’une plante, le pollen se loge dans les poils qui recouvrent son corps et peut donc être transporter vers une autre fleur, qu’il fertilise.<br>

        L’abeille ne visite qu’une même espèce de fleur à chacune de ses sorties, ainsi en une seule journée, une abeille peut pollinister des milliers de fleurs.<br>
        Certaines plantes comme les kiwis ont des pieds mâles et femelles séparés.<br> 

        Sans abeilles leur fécondation est impossible, les fleurs ne donneront pas de fruits. Pour le melon, le trèfle ou le tournesol, la pollinisation est indispensable.</p>
    
        <p class="colonne">Pour les plantes qui portent des fleurs mâles et femelles sur le même pied – la grande majorité – la pollinisation joue aussi un rôle très important : les fruits seront plus nombreux, plus beau et plus gros s’il y a eu une bonne pollinisation.
        70% des plantes sauvages et domestiques de l’hexagone sont dépendantes de la pollinisation et un tiers de la production agricole mondiale est directement assurée par la pollinisation.<br>

        Avec le soleil, l’eau et les nutriments du sol, la pollinisation est un facteur qui peut drastiquement limiter les rendements agricoles et la diversité des plantes sauvages.</p>

    </div>

    <h2 class="text-center">Le déclin des abeilles</h2>

    <div class="texte3">

        <p class="colonne">Il n’y a pas réponse toute faite au déclin des abeilles que l’on observe depuis déjà 60 ans avec une accélération ces 10 dernières années.<br>
        Les abeilles se nourrisent du néctar des fleurs. Avec la modernisation de l’agriculture et le grignottage des espaces sauvages par les villes, les haies et les fleurs en bord de champs sont moins nombreuses. Les abeilles ont moins de ressources pour se nourrir et leurs défenses contre les maladies et les parasites sont affaiblies.</p>

        <p class="colonne">Les pesticides ont également des impacts sur les abeilles. En 2012, l’Institut de Recherches Agronomiques (INRA) a démontré les effets d’une famille d’insecticides sur les abeilles, les néonicotinoïdes. Ces derniers, même à faible dose, perturbent l’orientation des abeilles qui ne parviennent plus à retrouver le chemin de leur ruche. Des champignons, des parasites (Varroa) et des prédateurs comme le frelon asiatique à pattes jaunes complètent le tableau des causes du déclin des abeilles en France.
        </p>

        <p class="colonne", id="colonne_couleur">
            Il est difficile d’avoir des statistiques fiables sur les pertes de ruches en France.<br>
            La production de miel témoigne des conséquences du déclin des abeilles.<br>
            En 2014, les récoltes de miel en France ont baissé de 50% à 80%, alors que 2012 et 2013 avaient déjà été des années particulièrement difficiles.  
        </p>
    </div>

    <h3 class="slug">Articles</h3>
        
         <div class="liens">
                <a href="http://www.lemonde.fr/planete/video/2014/08/02/le-declin-des-abeilles-explique-en-3-minutes_4465947_3244.html" target="_blank">Le Monde : le déclin des abeilles expliqué en 3 minutes.</a><br>

                <a href="https://fr.wikipedia.org/wiki/Abeille" target="_blank">Wikipédia : Abeille.</a><br>

                <a href="http://www.inra.fr/Grand-public/Ressources-et-milieux-naturels/Tous-les-dossiers/Abeilles-pollinisation-biodiversite-pesticides" target="_blank">INRA : Abeilles, reine de la survie : la pollinisation, la biodiversité, les pesticides.</a><br>

                <a href="http://www.unaf-apiculture.info/" target="_blank">Union nationale de l'apiculture française : L'actualité.</a><br>

                <a href="http://www.liberation.fr/economie/2015/03/19/si-vous-avez-des-carottes-c-est-grace-aux-abeilles_1224341" target="_blank">Libération : Si vous avez des carottes, c'est grâce aux abeilles.</a><br>

                <a href="http://www.actu-environnement.com/ae/news/ministere-agriculture-cruiser-osr-etude-inra-acta-cruiser-thiamethoxam-abeilles-15340.php4" target="_blank"> Ministètre de l'agriculture : La substance active du Cruiser intoxique les abeilles même à faible dose.</a><br>

                <a href="http://www.reporterre.net/En-ce-printemps-les-abeilles-de" target="_blank">Reporterre : En ce printemps, les abeillles de France sont au plus mal.</a><br>
            </div>       
</div>
<div class="contact3">
    <%= link_to (image_tag('home.png', title:"page d'accueil")), root_path, { :class=>"retour" } %>

    <%= link_to (image_tag('Bee1.jpg', width: 100, title:"contatez-nous")), form_path, { :class=>"call_to_action"} %> 
</div>